project_id = "qfnqmdmsapovxdjwdhsx"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54324

[functions.send-confirmation-email]
verify_jwt = false

[functions.confirm-subscription]
verify_jwt = false

[functions.notify-new-blog-post]
verify_jwt = false

[functions.notify-new-project]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false

[functions.generate-cover-image]
verify_jwt = false

[functions.google-tts]
verify_jwt = false

[functions.google-tts-voices]
verify_jwt = false
